# Generated by Django 6.0.1 on 2026-01-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Savol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Savollar',
            },
        ),
    ]
